spring.application.name=backend-TCC
# Dados de Conexão com o Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/TCC
spring.datasource.username=postgres
spring.datasource.password=JoAoPeDrO45!

# Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# A mágica: Cria/Atualiza as tabelas automaticamente baseado nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Para você ver no console do IntelliJ o que o Spring está fazendo no banco
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true