# Em vez de jdbc:postgresql://localhost:5432/oficina...
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuração do JWT
jwt.secret=${JWT_SECRET}